#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_armv7/libexec/gcc/arm-linux-gnueabihf/7.4.1:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_armv7/bin/arm-linux-gnueabihf-gcc \
    "$@"
