#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_aarch64/libexec/gcc/aarch64-linux-gnu/5.3.1:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_aarch64/bin/aarch64-linux-gnu-gcc \
    "$@"
