on: push
name: ci
jobs:
  local_build:
    name: "x86 build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: curtismuntz/bazel-action/bazelisk_1.1.0@bazelisk_1.1.0
        with:
          args: build //...

      - name: test
        uses: curtismuntz/bazel-action/bazelisk_1.1.0@bazelisk_1.1.0
        with:
          args: test //...

  cross_builds:
    name: cross compile build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ["aarch64", "armv7hf"]
    steps:
      - uses: actions/checkout@master

      - name: cross compile
        uses: curtismuntz/bazel-action/bazelisk_1.1.0@bazelisk_1.1.0
        with:
          args: build //... --config=${{ matrix.architecture }}
